var NombreDeUsuario
var Seguridad
function Seguridad(Seguridad) {
    Seguridad(1) = false
    Seguridad(2) = false
    Seguridad(3) = false
    Seguridad(4) = false
    Seguridad(5) = false
    Seguridad(6) = false
    Seguridad(7) = false
    Seguridad(8) = false
    Seguridad(9) = false
    Seguridad(10) = false
    Seguridad(11) = false
    Seguridad(12) = false
    Seguridad(13) = false
    Seguridad(14) = false
    Seguridad(15) = false
    Seguridad(16) = false
    Seguridad(17) = false
    Seguridad(18) = false
    Seguridad(19) = false
    Seguridad(20) = false
    Seguridad(21) = false
    Seguridad(22) = false
    Seguridad(23) = false
    Seguridad(24) = false
    Seguridad(25) = false
    Seguridad(26) = false
    Seguridad(27) = false
    Seguridad(28) = false
    Seguridad(29) = false
    Seguridad(30) = false
    Seguridad(31) = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
    Seguridad() = false
}
function Codigo(Seguridad) {
    if (Seguridad(1) == false) { }
}